// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmhYSflvxFIlKoZgfVxNS1LDugh9H4GNk',
    appId: '1:729694117523:web:11977fc13217384631f766',
    messagingSenderId: '729694117523',
    projectId: 'quiz-app-ee93a',
    authDomain: 'quiz-app-ee93a.firebaseapp.com',
    storageBucket: 'quiz-app-ee93a.firebasestorage.app',
    measurementId: 'G-RM3N1HMWGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVtO5a-vtLdcyRii6-om81d4KNNhYxi0s',
    appId: '1:729694117523:android:35e21a9833ef890b31f766',
    messagingSenderId: '729694117523',
    projectId: 'quiz-app-ee93a',
    storageBucket: 'quiz-app-ee93a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJdE9fFcLbAtUlhT-l2Y81grn8UE_-F1c',
    appId: '1:729694117523:ios:44780d8a998739ad31f766',
    messagingSenderId: '729694117523',
    projectId: 'quiz-app-ee93a',
    storageBucket: 'quiz-app-ee93a.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJdE9fFcLbAtUlhT-l2Y81grn8UE_-F1c',
    appId: '1:729694117523:ios:44780d8a998739ad31f766',
    messagingSenderId: '729694117523',
    projectId: 'quiz-app-ee93a',
    storageBucket: 'quiz-app-ee93a.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmhYSflvxFIlKoZgfVxNS1LDugh9H4GNk',
    appId: '1:729694117523:web:fad84efc9ea6ef2031f766',
    messagingSenderId: '729694117523',
    projectId: 'quiz-app-ee93a',
    authDomain: 'quiz-app-ee93a.firebaseapp.com',
    storageBucket: 'quiz-app-ee93a.firebasestorage.app',
    measurementId: 'G-EG6D1QQQ6Y',
  );
}
